{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./env.nix
    ./filesystem.nix
    ./home-manager.nix
    ./hyprland.nix
    ./locale.nix
    ./network.nix
    ./nh.nix
    ./nix.nix
    ./packages.nix
    ./stylix.nix
    ./timezone.nix
    ./user.nix
  ];
}
