backend = "fastresize"
color_space = "lch"
palette = "dark16"
check_contrast = true

[templates]
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/shared/colors.rasi'
waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors-wallust.css'
hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/themes/wallust.conf'
kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/colors.conf'
discord.template = 'colors-discord.css'
discord.target = '~/.config/vesktop/themes/wallust.css'
vscode.template = 'colors-vscode.json'
vscode.target = '~/.vscode/themes/colors-wallust.json'
pywal.template = 'colors-pywal'
pywal.target = '~/.cache/wal/colors'