backend = "fastresize"
color_space = "lch"
palette = "harddark16"

[templates]
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/shared/colors.rasi'
waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors-wallust.css'
hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/themes/wallust.conf'
kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/colors.conf'
